### ISSUE TITLE
AST nodes for regular expressions lack `regex` property

### ISSUE THREAD

**Issue by mathiasbynens** [devongovett/to-ast#1]
AST nodes for regular expressions should have a `regex` property that holds an object like `{ pattern: '…', flags: 'g' }`.

See https://github.com/estree/estree/blob/master/spec.md#regexliteral & https://github.com/shapesecurity/shift-spec/blob/56ec0f6020f039ca6f8c798f08be8227d6e068bb/spec.idl#L253-L256

**Comment by devongovett** [comment]
Seems like something to add to [ast-types](https://github.com/benjamn/ast-types)...

**Comment by mathiasbynens** [comment]
https://github.com/benjamn/ast-types/issues/103

**Comment by benjamn** [comment]
https://github.com/benjamn/ast-types/issues/103#issuecomment-91297829 :)

**Comment by devongovett** [comment]
Closed. Fixed by https://github.com/benjamn/ast-types/commit/ff48889db5896ccab4adaeee50aa1398c3c8979c.
